#ifndef CYRONENO_TEXT_OPENTYPE_TT_INSTRUCTION_OPCODE_MAP_H_
#define CYRONENO_TEXT_OPENTYPE_TT_INSTRUCTION_OPCODE_MAP_H_


namespace cyro {
namespace otf {



}
}

#endif  // CYRONENO_TEXT_OPENTYPE_TT_INSTRUCTION_OPCODE_MAP_H_